### ISSUE TITLE
is it possible to support scss?

### ISSUE THREAD

**Issue by craigcosmo** [y0ssar1an/CSS3_Syntax#24]
I set all my style sheet to CSS3 syntax. Apparently if I write css in scss syntax, sublime will red up my code. Is there anyway to tell sublime that's it's ok, don't be red.

<img width="612" alt="screen shot 2017-02-07 at 12 51 20 pm" src="https://cloud.githubusercontent.com/assets/538657/22679372/4179296c-ed34-11e6-8123-170d3f2aee5c.png">

**Comment by y0ssar1an** [comment]
This package is deprecated and dead. If you update to ST3, you can use my [CSS3](https://github.com/y0ssar1an/CSS3) package. It doesn't support SCSS, because that really requires a separate language definition. It does support nesting through [PostCSS-cssnext](http://cssnext.io/) if you're into that.
